// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75378idO1AyFZlj8kZiwnoA_1eb-L1xE',
    appId: '1:1069327607454:web:d795330e5b178a4df33d8f',
    messagingSenderId: '1069327607454',
    projectId: 'rosary-87ae9',
    authDomain: 'rosary-87ae9.firebaseapp.com',
    storageBucket: 'rosary-87ae9.appspot.com',
    measurementId: 'G-8Y46Y9NMCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGfH8OymCvg1d70Sy4w52UGc6evNgiqMs',
    appId: '1:1069327607454:android:2e634364e1f55c69f33d8f',
    messagingSenderId: '1069327607454',
    projectId: 'rosary-87ae9',
    storageBucket: 'rosary-87ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsqDIpvytBx06DLzdALHjDPogTMYOKQk',
    appId: '1:1069327607454:ios:b2c329cc3e097ae3f33d8f',
    messagingSenderId: '1069327607454',
    projectId: 'rosary-87ae9',
    storageBucket: 'rosary-87ae9.appspot.com',
    iosBundleId: 'com.rosarysoftnergy.app',
  );
}
